// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import AuthProvider from "./AuthProvider";
import SocketProvider from "@/context/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meowๆ",
  description: "Generated by create next app",
};

const imagesToPreload = [
  "/img/1.jpg",
  "/img/2.jpg",
  "/img/3.jpg",
  "/img/4.jpg",
  "/img/5.jpg",
  "/img/6.jpg",
  "/img/7.jpg",
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Preload images */}
        {imagesToPreload.map((src) => (
          <link key={src} rel="preload" href={src} as="image" />
        ))}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SocketProvider>
          <AuthProvider>
            <Providers>{children}</Providers>
          </AuthProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
